name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: false

      - name: Install Dependencies
        run: |
          bundle install
          echo "Listing content of Gemfile.lock:"
          cat Gemfile.lock

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build
          sleep 3 # sleep to finish before rsync

      - name: List generated files
        run: |
          echo "Listing all generated files:"
          ls -R _site/

      - name: Checkout gh-pages branch
        run: |
          git fetch origin
          git checkout gh-pages || git checkout -b gh-pages

      - name: Copy built site to gh-pages
        run: |
          rsync -av --delete _site/ .

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add --all
          git commit -m "Deploy site"
          git push origin gh-pages --force
