name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: false

      - name: Install specific Bundler version
        run: gem install bundler -v 2.2.18

      - name: Install Dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --config _config.yml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./_site
